export const en = {
  brandSubtitle: "Purchase Approval Management", navPrimary: "Primary navigation", homeLabel: "PurchaseFlow home", dashboardNav: "Dashboard", newRequestNav: "New Request", mailboxNav: "Demo Mailbox",
  languageSelector: "Select language", spanish: "Spanish", english: "English", loading: "Loading…", unavailable: "Unavailable",
  dashboardEyebrow: "Overview", dashboardTitle: "Purchase Requests", dashboardSubtitle: "Track requests and approval progress.", newPurchaseRequest: "New Purchase Request", loadingRequests: "Loading purchase requests…", noRequests: "No purchase requests yet", noRequestsDescription: "Create the first request to begin an approval workflow.", amount: "Amount", requestedBy: "Requested by", created: "Created", approvalProgress: "Approval progress", approvalsCount: "{signed} / 3 approvals", rejectedProgress: "{signed} approved · {cancelled} cancelled", viewDetails: "View Details",
  newWorkflow: "New workflow", createTitle: "Create Purchase Request", createSubtitle: "Provide the request details and exactly three approvers.", requestInformation: "Request information", title: "Title", description: "Description", requestedByLabel: "Requested By", approvers: "Approvers", rolesDifferentHelp: "All three roles must be different.", requiredThree: "3 required", approverNumber: "Approver {number}", name: "Name", email: "Email", role: "Role", rolePlaceholder: "e.g. Finance", loadTestData: "Load Test Data", clearForm: "Clear Form", createRequest: "Create Request", creating: "Creating…",
  validationRequestFields: "Complete all request information fields.", validationAmount: "Amount must be greater than zero.", validationApproverFields: "Complete all fields for approver {number}.", validationEmail: "Enter a valid email for approver {number}.", validationRoles: "Approver roles must be different.", unableCreate: "Unable to create request.",
  purchaseRequest: "Purchase request", loadingDetail: "Loading request details…", requestNotFound: "Purchase request not found.", backDashboard: "Back to Dashboard", createdSuccess: "Purchase request created successfully.", requestDetails: "Request details", createdAt: "Created at", requestId: "Request ID", preparingPdf: "Preparing PDF…", downloadPdf: "Download Evidence PDF", approvalProgressTitle: "Approval Progress", approvalsCompleted: "{signed} of 3 approvals completed", decided: "Decided {date}", cancelledReason: "Cancelled because the request was rejected.", unableLoadRequest: "Unable to load request.", missingRequestId: "Request ID is missing.",
  technicalDemo: "Technical demo", mailboxTitle: "Demo Mailbox", mailboxSubtitle: "Use simulated messages to complete approval workflows.", demoOnly: "Demo only", demoWarning: "this mailbox exposes simulated OTP codes and approval links.", loadingMail: "Loading simulated mail…", mailboxEmpty: "Mailbox is empty", mailboxEmptyDescription: "Create a purchase request to generate approval emails.", requestPrefix: "Request:", approvalMessages: "{count} approval messages", messageCount: "{count} messages", viewEmail: "View Email", hideEmail: "Hide Email", subject: "Subject", requestClosed: "Request closed", approvedAction: "Approved", rejectedAction: "Rejected", openApproval: "Open Approval", unableMailbox: "Unable to load demo mailbox.",
  mailboxFilters: "Mailbox filters", mailboxSearchPlaceholder: "Search by title, requester, email or ID...", mailboxStatus: "Status", mailboxPending: "Pending", mailboxCompleted: "Completed", mailboxRejected: "Rejected", sortBy: "Sort by", sortNewest: "Newest", sortOldest: "Oldest", sortTitleAsc: "Title A-Z", sortTitleDesc: "Title Z-A", mailboxShowing: "Showing {shown} of {total} requests", previous: "Previous", next: "Next", pageOf: "Page {page} of {total}", mailboxPagination: "Mailbox pagination", mailboxNoMatches: "No requests match these filters.", mailboxChangeFilters: "Try changing your search or clearing the filters.",
  invalidLink: "Invalid approval link", invalidLinkDescription: "This link is missing required information. Request a new link from the purchase requester.", checkingStatus: "Checking approval status…", approvalLink: "Approval link", decisionAlready: "Decision already recorded", alreadyRejected: "This request has already been rejected. No further action is available.", alreadyApproved: "This approval has already been completed. No further action is required.", decisionRecorded: "Decision recorded", approvalSuccess: "Approval registered successfully.", requestRejected: "Request rejected.", savedDecision: "Your decision has been saved. No further action is required.", secureVerification: "Secure verification", verificationTitle: "Approval Verification", expiredTitle: "Verification code expired", expiredDescription: "Your verification code has expired.", requestNewCode: "Request a new code to continue.", enterCode: "Enter the 6-digit code sent to your email.", newCodeSent: "New verification code sent.", checkMailbox: "Check Demo Mailbox for the new OTP.", sending: "Sending…", resendOtp: "Resend OTP", openMailbox: "Open Demo Mailbox", verificationCode: "Verification code", verifying: "Verifying…", verifyCode: "Verify Code", decisionRequired: "Decision required", approvingAs: "Approving as", processing: "Processing…", reject: "Reject", approve: "Approve", rejectConfirm: "Are you sure you want to reject this request?", codeIncomplete: "Enter the complete 6-digit code.", invalidCredentials: "The verification code or approval link is invalid.", expiredError: "This verification code has expired.", operationConflict: "This request no longer allows this operation.", genericError: "Something went wrong. Please try again.",
  filters: "Filters", search: "Search", searchPlaceholder: "Search by title, description or ID...", requestStatus: "Request status", all: "All", requestedByFilter: "Requested by", requestedByPlaceholder: "Requester name", dateFrom: "Date from", dateTo: "Date to", applyFilters: "Apply filters", clearFilters: "Clear filters", results: "{count} results", oneResult: "1 result", noResults: "No results", noFilterMatches: "No requests match these filters.", changeFilters: "Try changing or clearing your search criteria.",
  rejectionSuccess: "Rejection registered successfully.", requestStillPending: "The request is still pending other approvals.", allApprovalsCompleted: "All approvals have been completed.",
  notFoundTitle: "Page not found", notFoundDescription: "The page you requested does not exist.", goDashboard: "Go to Dashboard",
  statusPending: "Pending", statusApproved: "Approved", statusRejected: "Rejected", statusCompleted: "Completed", statusCancelled: "Cancelled",
} as const;

export type TranslationKey = keyof typeof en;
export const es: Record<TranslationKey, string> = {
  brandSubtitle: "Gestión de aprobaciones de compra", navPrimary: "Navegación principal", homeLabel: "Inicio de PurchaseFlow", dashboardNav: "Inicio", newRequestNav: "Nueva solicitud", mailboxNav: "Buzón de demostración",
  languageSelector: "Seleccionar idioma", spanish: "Español", english: "Inglés", loading: "Cargando…", unavailable: "No disponible",
  dashboardEyebrow: "Resumen", dashboardTitle: "Solicitudes de compra", dashboardSubtitle: "Consulta las solicitudes y su progreso de aprobación.", newPurchaseRequest: "Nueva solicitud de compra", loadingRequests: "Cargando solicitudes de compra…", noRequests: "Aún no hay solicitudes de compra", noRequestsDescription: "Crea la primera solicitud para iniciar un flujo de aprobación.", amount: "Monto", requestedBy: "Solicitado por", created: "Creada", approvalProgress: "Progreso de aprobación", approvalsCount: "{signed} / 3 aprobaciones", rejectedProgress: "{signed} aprobados · {cancelled} cancelados", viewDetails: "Ver detalles",
  newWorkflow: "Nuevo flujo", createTitle: "Crear solicitud de compra", createSubtitle: "Ingresa los datos de la solicitud y exactamente tres aprobadores.", requestInformation: "Información de la solicitud", title: "Título", description: "Descripción", requestedByLabel: "Solicitado por", approvers: "Aprobadores", rolesDifferentHelp: "Los tres roles deben ser diferentes.", requiredThree: "3 requeridos", approverNumber: "Aprobador {number}", name: "Nombre", email: "Correo electrónico", role: "Rol", rolePlaceholder: "p. ej., Finanzas", loadTestData: "Cargar datos de prueba", clearForm: "Limpiar formulario", createRequest: "Crear solicitud", creating: "Creando…",
  validationRequestFields: "Completa todos los campos de información de la solicitud.", validationAmount: "El monto debe ser mayor que cero.", validationApproverFields: "Completa todos los campos del aprobador {number}.", validationEmail: "Ingresa un correo válido para el aprobador {number}.", validationRoles: "Los roles de los aprobadores deben ser diferentes.", unableCreate: "No fue posible crear la solicitud.",
  purchaseRequest: "Solicitud de compra", loadingDetail: "Cargando detalles de la solicitud…", requestNotFound: "No se encontró la solicitud de compra.", backDashboard: "Volver al inicio", createdSuccess: "Solicitud de compra creada correctamente.", requestDetails: "Detalles de la solicitud", createdAt: "Fecha de creación", requestId: "ID de solicitud", preparingPdf: "Preparando PDF…", downloadPdf: "Descargar PDF de evidencia", approvalProgressTitle: "Progreso de aprobación", approvalsCompleted: "{signed} de 3 aprobaciones completadas", decided: "Decisión: {date}", cancelledReason: "Cancelado porque la solicitud fue rechazada.", unableLoadRequest: "No fue posible cargar la solicitud.", missingRequestId: "Falta el ID de la solicitud.",
  technicalDemo: "Demostración técnica", mailboxTitle: "Buzón de demostración", mailboxSubtitle: "Usa los mensajes simulados para completar flujos de aprobación.", demoOnly: "Solo demostración", demoWarning: "este buzón expone códigos OTP y enlaces de aprobación simulados.", loadingMail: "Cargando correo simulado…", mailboxEmpty: "El buzón está vacío", mailboxEmptyDescription: "Crea una solicitud de compra para generar correos de aprobación.", requestPrefix: "Solicitud:", approvalMessages: "{count} mensajes de aprobación", messageCount: "{count} mensajes", viewEmail: "Ver correo", hideEmail: "Ocultar correo", subject: "Asunto", requestClosed: "Solicitud cerrada", approvedAction: "Aprobado", rejectedAction: "Rechazado", openApproval: "Abrir aprobación", unableMailbox: "No fue posible cargar el buzón de demostración.",
  mailboxFilters: "Filtros del buzón", mailboxSearchPlaceholder: "Buscar por título, solicitante, correo o ID...", mailboxStatus: "Estado", mailboxPending: "Pendientes", mailboxCompleted: "Completadas", mailboxRejected: "Rechazadas", sortBy: "Ordenar por", sortNewest: "Más recientes", sortOldest: "Más antiguas", sortTitleAsc: "Título A-Z", sortTitleDesc: "Título Z-A", mailboxShowing: "Mostrando {shown} de {total} solicitudes", previous: "Anterior", next: "Siguiente", pageOf: "Página {page} de {total}", mailboxPagination: "Paginación del buzón", mailboxNoMatches: "No encontramos solicitudes con estos filtros.", mailboxChangeFilters: "Intenta cambiar la búsqueda o limpiar los filtros.",
  invalidLink: "Enlace de aprobación inválido", invalidLinkDescription: "A este enlace le falta información requerida. Solicita un nuevo enlace al solicitante.", checkingStatus: "Consultando el estado de aprobación…", approvalLink: "Enlace de aprobación", decisionAlready: "Decisión ya registrada", alreadyRejected: "Esta solicitud ya fue rechazada. No hay más acciones disponibles.", alreadyApproved: "Esta aprobación ya fue completada. No se requiere ninguna acción adicional.", decisionRecorded: "Decisión registrada", approvalSuccess: "Aprobación registrada correctamente.", requestRejected: "Solicitud rechazada.", savedDecision: "Tu decisión fue guardada. No se requiere ninguna acción adicional.", secureVerification: "Verificación segura", verificationTitle: "Verificación de aprobación", expiredTitle: "El código de verificación expiró", expiredDescription: "Tu código de verificación expiró.", requestNewCode: "Solicita un nuevo código para continuar.", enterCode: "Ingresa el código de 6 dígitos enviado a tu correo.", newCodeSent: "Nuevo código de verificación enviado.", checkMailbox: "Consulta el buzón de demostración para obtener el nuevo OTP.", sending: "Enviando…", resendOtp: "Reenviar código", openMailbox: "Abrir buzón de demostración", verificationCode: "Código de verificación", verifying: "Verificando…", verifyCode: "Verificar código", decisionRequired: "Decisión requerida", approvingAs: "Aprobando como", processing: "Procesando…", reject: "Rechazar", approve: "Aprobar", rejectConfirm: "¿Confirmas que deseas rechazar esta solicitud?", codeIncomplete: "Ingresa el código completo de 6 dígitos.", invalidCredentials: "Código o credenciales de aprobación inválidas.", expiredError: "El código de verificación expiró.", operationConflict: "Esta solicitud ya no permite esta operación.", genericError: "Ocurrió un error. Inténtalo nuevamente.",
  filters: "Filtros", search: "Buscar", searchPlaceholder: "Buscar por título, descripción o ID...", requestStatus: "Estado de la solicitud", all: "Todos", requestedByFilter: "Solicitado por", requestedByPlaceholder: "Nombre del solicitante", dateFrom: "Fecha desde", dateTo: "Fecha hasta", applyFilters: "Aplicar filtros", clearFilters: "Limpiar filtros", results: "{count} resultados", oneResult: "1 resultado", noResults: "Sin resultados", noFilterMatches: "No encontramos solicitudes con estos filtros.", changeFilters: "Intenta modificar o limpiar los criterios de búsqueda.",
  rejectionSuccess: "Rechazo registrado correctamente.", requestStillPending: "La solicitud continúa pendiente de otras aprobaciones.", allApprovalsCompleted: "Todas las aprobaciones fueron completadas.",
  notFoundTitle: "Página no encontrada", notFoundDescription: "La página solicitada no existe.", goDashboard: "Ir al inicio",
  statusPending: "Pendiente", statusApproved: "Aprobado", statusRejected: "Rechazado", statusCompleted: "Completado", statusCancelled: "Cancelado",
};

export const translations = { es, en } as const;
